#!/usr/bin/env python3
"""Generate the mesh master key and the firmware header that carries it.

    .venv/bin/python scripts/gen_mesh_key.py

Writes:
    config/mesh.key                          server side, chmod 600
    firmware/esp32_rti_node/mesh_key.h       compiled into every node

Every node gets the SAME master key and derives its own per-node keys from it
via HKDF. That is what removes per-device provisioning: one binary, flashed
unchanged, and any node can derive any peer's key to verify its beacons.

The trade-off is explicit and worth understanding before you deploy: physical
possession of one node yields the master key, and therefore the whole mesh. If
that matters for your threat model, enable ESP32 flash encryption and secure
boot so the key cannot be read out of a stolen node, and rotate with --rotate
if you ever suspect compromise.
"""
from __future__ import annotations

import argparse
import os
import stat
import sys
from datetime import datetime
from pathlib import Path

from ..mesh.crypto import MASTER_KEY_BYTES, generate_master_key

HEADER_TEMPLATE = """\
// Generated by scripts/gen_mesh_key.py on {when}
// SECRET. Do not commit this file; .gitignore already excludes it.
#pragma once
#include <stdint.h>

// Mesh master key. Identical on every node; per-node keys are derived from it.
static const uint8_t MESH_MASTER_KEY[{n}] = {{
    {body}
}};
static const size_t MESH_MASTER_KEY_LEN = {n};
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--key-file", default="config/mesh.key")
    ap.add_argument("--header", default="firmware/esp32_rti_node/mesh_key.h")
    ap.add_argument("--rotate", action="store_true",
                    help="overwrite an existing key (every node must be reflashed)")
    args = ap.parse_args(argv)

    key_path = Path(args.key_file)
    if key_path.exists() and not args.rotate:
        print(f"{key_path} already exists. Refusing to overwrite it.\n"
              f"Rotating the key requires reflashing every node, so it is not "
              f"something to do by accident.\nUse --rotate if you mean it.",
              file=sys.stderr)
        return 1

    key = generate_master_key()

    key_path.parent.mkdir(parents=True, exist_ok=True)
    # Create with 0600 from the start rather than chmod after: a world-readable
    # window, however brief, is a window.
    fd = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write(key.hex() + "\n")
    os.chmod(key_path, stat.S_IRUSR | stat.S_IWUSR)

    hdr = Path(args.header)
    hdr.parent.mkdir(parents=True, exist_ok=True)
    body = ", ".join(f"0x{b:02x}" for b in key)
    wrapped = "\n    ".join(body[i:i + 72] for i in range(0, len(body), 72))
    hdr.write_text(HEADER_TEMPLATE.format(
        when=datetime.now().isoformat(timespec="seconds"),
        n=MASTER_KEY_BYTES, body=wrapped))
    os.chmod(hdr, stat.S_IRUSR | stat.S_IWUSR)

    print(f"master key   : {MASTER_KEY_BYTES * 8}-bit, generated with secrets.token_bytes")
    print(f"server key   : {key_path}  (mode 600)")
    print(f"firmware key : {hdr}  (mode 600)")
    print("\nnext:")
    print("  1. flash every node - the header is picked up automatically")
    print("  2. start the dashboard; it reads config/mesh.key by default")
    print("\nNeither file is committed: both are in .gitignore.")
    if args.rotate:
        print("\nROTATED. Every node must be reflashed or it will be rejected.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
