#!/usr/bin/env python3
"""Generate firmware/esp32_rti_node/config.h and sanity-check the settings.

    .venv/bin/python scripts/setup_firmware.py --ssid MyNet_2G --password 'secret'

Server IP defaults to this machine's address on the WiFi interface, which is
almost always what you want: the nodes report to whatever runs the dashboard.
"""
from __future__ import annotations

import argparse
import os
import re
import stat
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

TEMPLATE = '''// Generated by scripts/setup_firmware.py - do not commit (holds your WiFi password)
#pragma once

#define CFG_WIFI_SSID   "{ssid}"
#define CFG_WIFI_PASS   "{password}"

#define CFG_SERVER_IP   "{server_ip}"
#define CFG_SERVER_PORT {port}

#define CFG_BEACON_INTERVAL_MS {beacon}
#define CFG_REPORT_INTERVAL_MS {report}
#define CFG_PEER_STALE_MS      {stale}

#define CFG_LED_PIN {led}
'''


def local_ip(iface: str = "wlan0") -> str | None:
    try:
        out = subprocess.run(["ip", "-4", "addr", "show", iface],
                             capture_output=True, text=True).stdout
    except FileNotFoundError:
        return None
    m = re.search(r"inet (\d+\.\d+\.\d+\.\d+)", out)
    return m.group(1) if m else None


def band_of(iface: str = "wlan0") -> tuple[str, int] | None:
    try:
        out = subprocess.run(["iw", "dev", iface, "link"],
                             capture_output=True, text=True).stdout
        f = re.search(r"freq: (\d+)", out)
        s = re.search(r"SSID: (.+)", out)
        if f:
            mhz = int(f.group(1))
            return (s.group(1).strip() if s else "?", mhz)
    except FileNotFoundError:
        pass
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ssid", help="2.4 GHz SSID the nodes should join")
    ap.add_argument("--password", help="WiFi password")
    ap.add_argument("--server-ip", default=None,
                    help="where the dashboard runs (default: this machine)")
    ap.add_argument("--port", type=int, default=9999)
    ap.add_argument("--iface", default="wlan0")
    ap.add_argument("--beacon-ms", type=int, default=40)
    ap.add_argument("--report-ms", type=int, default=200)
    ap.add_argument("--stale-ms", type=int, default=3000)
    ap.add_argument("--led-pin", type=int, default=2,
                    help="-1 to disable (ESP32-S3 boards often need this)")
    ap.add_argument("--out", default="firmware/esp32_rti_node/config.h")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    out = Path(args.out)
    if out.exists() and not args.force:
        print(f"{out} exists; use --force to overwrite", file=sys.stderr)
        return 1

    server_ip = args.server_ip or local_ip(args.iface)
    if not server_ip:
        print(f"could not determine this machine's IP on {args.iface}; "
              f"pass --server-ip", file=sys.stderr)
        return 1

    if not args.ssid or args.password is None:
        print("error: --ssid and --password are required", file=sys.stderr)
        link = band_of(args.iface)
        if link:
            ssid, mhz = link
            band = "2.4 GHz" if mhz < 3000 else "5 GHz"
            print(f"\nthis machine is on '{ssid}' at {mhz} MHz ({band})",
                  file=sys.stderr)
            if mhz >= 3000:
                print("NOTE: that is 5 GHz. ESP32 is 2.4 GHz only, so the nodes\n"
                      "      need your 2.4 GHz SSID - which may be a different\n"
                      "      name, or the same one if your router band-steers.",
                      file=sys.stderr)
        return 1

    out.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as fh:
        fh.write(TEMPLATE.format(
            ssid=args.ssid, password=args.password, server_ip=server_ip,
            port=args.port, beacon=args.beacon_ms, report=args.report_ms,
            stale=args.stale_ms, led=args.led_pin))
    os.chmod(out, stat.S_IRUSR | stat.S_IWUSR)

    print(f"wrote {out} (mode 600, gitignored)")
    print(f"  SSID      : {args.ssid}")
    print(f"  server    : {server_ip}:{args.port}")
    print(f"  beacon    : every {args.beacon_ms} ms  (~{1000/args.beacon_ms:.0f}/s)")
    print(f"  report    : every {args.report_ms} ms  ({1000/args.report_ms:.0f}/s)")

    link = band_of(args.iface)
    if link and link[1] >= 3000:
        print(f"\nNOTE: this machine is on 5 GHz ({link[1]} MHz). That is fine -\n"
              f"      the nodes just need to reach {server_ip} over the LAN - but\n"
              f"      confirm '{args.ssid}' really is a 2.4 GHz network.")
    if not Path("config/mesh.key").exists():
        print("\nNEXT: run scripts/gen_mesh_key.py before flashing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
